import { z } from "zod";

export function getPlanToolDescription() {
  return {
    description: `Update the status of plan steps. Use this to track which steps are in progress or completed. The initial plan is generated by generate_plan.`,
    inputSchema: z.object({
      steps: z.array(z.object({
        id: z.string().optional().describe("Step ID (auto-generated if not provided)"),
        description: z.string().describe("What needs to be researched or analyzed"),
        status: z.enum(["pending", "in_progress", "completed"]).optional().default("pending"),
        agent_ids: z.array(z.string()).optional().describe("Agent IDs assigned to this step")
      })).describe("Array of plan steps"),
      mode: z.enum(["replace", "append"]).describe("replace: overwrite plan, append: add to existing")
    })
  };
}
